### ISSUE TITLE
error: suite "files" does not contain any tests

### ISSUE THREAD

**Issue by jianzhangbjz** [openshift/openshift-tests#37]
[provide a description of the issue]
The `openshift-tests` binary cannot run any tests in the disconnected cluster.

##### Version
[provide output of the `openshift version` or `oc version` command]
openshift-tests version: v4.1.0+980671d-2626-dirty

##### Steps To Reproduce
Details: http://10.0.96.174:8080/job/olm-test/234/console

##### Current Result

```console
16:26:39 [INFO] hack/build-go.sh exited with code 0 after 00h 02m 16s
16:26:39 I0423 04:26:39.738267    7057 test_context.go:423] Tolerating taints "node-role.kubernetes.io/master" when considering if nodes are ready
16:26:39 openshift-tests version: v4.1.0+980671d-2626-dirty
16:26:41 I0423 04:26:41.038522    7060 test_context.go:423] Tolerating taints "node-role.kubernetes.io/master" when considering if nodes are ready
16:26:41 error: suite "files" does not contain any tests
```
##### Expected Result
The `openshift-tests` binary runs well.

**Comment by kuiwang02** [comment]
@jianzhangbjz  you take openshift/orig repo and input Critical in IMPORTANCE, and after checking the case code, there is no Critical for OLM cases, so does not contain any tests.

**Comment by jianzhangbjz** [comment]
Got it, thanks for your information!
